[project]
name = "exchangerate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.5",
    "gradio>=5.37.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.11.0",
]
